### ISSUE TITLE
[Frage] Linux kompatibel?

### ISSUE THREAD

**Issue by miiiiiYT** [12tom12/minecraft-web-GUI#1]
Ist der Server auch Linux kompatibel, ich würde das ganze auf einem Raspberry Pi laufen lassen.

Danke schonmal im voraus.

**Comment by tomtactom** [comment]
Hey @miiiiiYT,
Ich baue das ganze momentan so um, dass es auch auf Linux kompatibel ist. Bei einem Raspberry Pi würde ich dir schon den 4er empfehlen, da die anderen alle zu wenig RAM haben. Falls du Hilfe brauchst, sag einfach Bescheid. ;)

Viele Grüße
Tom

**Comment by miiiiiYT** [comment]
Cool, ich hatte so oder so das auf einem Pi 4 geplant. Hilfe würde ich auch gerne annehmen, ich komme mit dem README nicht so zurecht, aber das hat Zeit bis das Repo Linux kompatibel ist, wenn du das schon planst.

LG

**Comment by tomtactom** [comment]
Ich habe jetzt schon das ein bisschen umgebaut, leider bekomme ich den Server allerdings nicht gestartet und gestoppt und kann die einzelnen Spieler nicht anzeigen lassen. Rcon Befehle senden und die Logs ansehen geht jedoch.
Momentan arbeite ich an anderen Projekten. Schreib mich am besten auf WhatsApp mal an, da kann ich dir besser helfen ggf. auch per Telefon ;). Da kann ich dir beim Einrichten helfen.
+49 178 8724382

**Comment by miiiiiYT** [comment]
Hast du auch Telegram? Sonst schreib Mal @miiiiiYT an
